### ISSUE TITLE
App doesn't load due to Cross Origin Embedder Policy change in Helmet v5

### ISSUE THREAD

**Issue by mterrel** [feathersjs/feathers-chat-ts#108]
### Steps to reproduce

1. Clone repo (crow branch)
2. `npm install`
3. `npm run dev`
4. Open browser on http://localhost:3030

### Expected behavior

The chat app login page should display in the browser.

### Actual behavior

The browser shows a completely blank page. The browser console shows multiple instances of the error:

```
Failed to load resource: net::ERR_BLOCKED_BY_RESPONSE.NotSameOriginAfterDefaultedToSameOriginByCoep
```

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

The part we really care about here is: `helmet@5.0.2`

But for completeness, Feathers components from `npm list`:
```
├─┬ @feathersjs/authentication@4.5.12
│ ├─┬ @feathersjs/transport-commons@4.5.12
├─┬ @feathersjs/authentication-local@4.5.12
├─┬ @feathersjs/authentication-oauth@4.5.12
├─┬ @feathersjs/configuration@4.5.12
├─┬ @feathersjs/errors@4.5.12
├─┬ @feathersjs/express@4.5.12
│ ├── @feathersjs/commons@4.5.12
├─┬ @feathersjs/feathers@4.5.12
├─┬ @feathersjs/socketio@4.5.13
├─┬ feathers-nedb@6.0.0
│ ├─┬ @feathersjs/adapter-commons@4.5.11
```

**NodeJS version**: 14.18.2

**Operating System**: Amazon Linux 2

**Browser Version**: Chrome Linux 99.0.4844.74

**React Native Version**: N/A

**Module Loader**: N/A

### Analysis

* None of the external (cross-origin) resources that the chat app uses are allowed to load. So that includes base.css, chat.css, moment.js, and feathers.js. This causes an immediate exception running client.js because `feathers` is undefined.
* Note that the inability to load external resources also extends to images like the Feathers logo and Gravatars. But those don't load until later.
* The problem is that Helmet v5 has some pretty major breaking changes in their default settings. (See https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md) They've increased their default security posture across the board. But the key issue that causes the above error is that they changed the Cross Origin Embedder Policy to `Cross-Origin-Embedder-Policy: require-corp`, which means that `index.html` can only load resources from the same origin or resources explicitly marked as loadable from another origin. (See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy for more info on COEP)

### Suggested fixes

I see two possible fixes. If you let me know your preference, I'm happy to submit a PR.

1. Accept the increase in security from helmet and correctly mark all external resources using the `crossorigin` attribute or using the `Cross-Origin-Resource-Policy` header on requests. This is definitely the more correct, secure, and "let's teach good practices" option. However, this choice is likely to frustrate all but the most experienced web developers as soon as they add an `<img>` tag with an external origin or try to `fetch` any external resource. I certainly didn't know immediately what the Chrome error meant or how to fix it.

2. Relax (only) the COEP policy on helmet back to the previous default state by passing `crossOriginEmbedderPolicy: false` to helmet. This is less secure but definitely more developer friendly. This is the option I'd suggest, possibly with a note in the README about security that points out this option and also points toward the helmet website. (If you want me to submit this as a PR, let me know if you want the README change too.)

**Comment by daffl** [comment]
Proper cross origin configuration should now be available in the latest version which has been moved to https://github.com/feathersjs/feathers-chat/
