### ISSUE TITLE
[FR] Archive this repo.

### ISSUE THREAD

**Issue by FossPrime** [feathersjs/feathers-chat-ts#119]
This is an extremely confusing repo, that serves no purpose that I can see.

Yet, the bots keep making branches making it seem like this is the best active repo for educational and demonstration purposes.

![Screenshot_20221101-111232](https://user-images.githubusercontent.com/876076/199144227-72cf9c24-6cb3-4658-b7f2-67921c4c4e87.png)

... We can always go back if someone complains... 

<details>
No one will. 
</spoiler>

**Comment by daffl** [comment]
Very good point. This is done now.
