### ISSUE TITLE
Can`t login, get error: "There was an error: Invalid login"

### ISSUE THREAD

**Issue by igorgidea** [feathersjs/feathers-chat-ts#45]
When i try sign up and login i get error 
{
  "name": "NotAuthenticated",
  "message": "Invalid login",
  "code": 401,
  "className": "not-authenticated",
  "errors": {}
}

### Steps to reproduce
1. Clone the chat repository (typescript version) and cd into it
2. install dependencies, run npm i 
3. run npm start
4. Enter email and password and press "Sign up and log in" button as result get error
### System configuration
**NodeJS version**:
v12.18.0
**Operating System**:
Windows 10 x64
**Browser Version**:
Google Chrome version 83.0.4103.97

**Comment by daffl** [comment]
Try removing the `data` folder and restarting the application. The process also needs permissions to write to the current folder.

**Comment by igorgidea** [comment]
I have deleted data directory, restart the application, try again doing sign up and login, but still no luck
![изображение](https://user-images.githubusercontent.com/20354531/84696438-2ff6b600-af55-11ea-84cb-ff4052191651.png)
"data" directory has been created and fulfilled with user data:
![изображение](https://user-images.githubusercontent.com/20354531/84696899-e490d780-af55-11ea-976e-f6e32cba88f8.png)

**Comment by igorgidea** [comment]
Additionally, I tried to generate a new project with authorization using feathers cli and I get the same error - I can’t log in. By the way, everything works under Ubuntu.

**Comment by daffl** [comment]
That's why I said it is probably a file permission issue. The `data` folder needs to be writeable by the Node process.

**Comment by igorgidea** [comment]
In my [comment](https://github.com/feathersjs/feathers-chat-ts/issues/45#issuecomment-644327186) above i wrote that `"data" directory has been created and fulfilled with user data` i suppose its means Node process can write, is it? How can I verify that feathers have a problem with permissions?
I hope there are no reason for permission problems, many others nodejs application works just fine on my windows 10 some of them works with files all projects placed inside one root folder.

**Comment by daffl** [comment]
Or read it. Since this is the first time I'm seeing this, I'm fairly sure it is a permission problem.
